version: '3.7'

volumes:
  bookshelf:
    name: bookshelf-volume 
    external: true
  bundle:
    name: bundle-volume
    external: true

services:
  app:
    volumes:
      - bookshelf:/bookshelf
      - bundle:/vendor/bundle
