version: '3.7'

volumes:
  bundle:
    name: bookshelf-bundle
    driver: local
    driver_opts:
      type: none
      device: /Users/koboritomoyuki/Programs/Docker/data_volumes/bundle
      o: bind
  bookshelf:
    name: bookshelf-local
    driver: local
    driver_opts:
      type: none
      device: /Users/koboritomoyuki/Programs/bookshelf

      o: bind

services:
  app:
    build: ./docker
    image: hanami
    working_dir: /bookshelf
    environment:
      HANAMI_ENV: development
      BUNDLE_APP_CONFIG: /bookshelf/.bundle
    volumes:
      - bookshelf:/bookshelf
      - bundle:/vendor/bundle
    ports:
      - 2300
    command: 'bundle exec hanami server --host 0.0.0.0'
